// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciplmijogdyjhvozlsmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcGxtaWpvZ2R5amh2b3psc21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDkyMzUsImV4cCI6MjA2OTE4NTIzNX0.1scM-5JtSF-KONPCQ_larG4TIPiBJY389o61oIDwM_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});